# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FinalProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FinalProject
  pod 'SwiftLint'
  pod 'Firebase/Core', :inhibit_warnings => true
  pod 'Firebase/Auth', :inhibit_warnings => true
  pod 'Firebase/Database', :inhibit_warnings => true
  pod 'Firebase/Storage'
end
